### ISSUE TITLE
Can't seem to find it in package control?

### ISSUE THREAD

**Issue by jubalm** [arcticicestudio/nord-sublime-text#10] opened 2018-01-20 13:04 UTC
https://packagecontrol.io/search/nord

**Comment by ghost** [comment] 2018-01-20 14:48
Duplicate #7

**Comment by arcticicestudio** [comment] 2018-01-20 20:31
Thanks for your contribution :+1: , but like @carlevison already mentioned this is a duplicate of #7. Please subscribe/read the linked issue.

**Closed as completed by arcticicestudio** 2018-01-20 20:31 UTC
Labels: resolution-duplicate
